framework:
    cache:
        prefix_seed: gardenmanager

        pools:
            permission.cache:
                adapter: cache.adapter.redis_tag_aware
                provider: '%env(REDIS_CACHE_DSN)%'
                default_lifetime: 3600
