twig_component:
    anonymous_template_directory: 'components/anonymous'
    defaults:
        GardenManager\Shared\Infrastructure\Twig\Components\: 'components/shared/'
        GardenManager\Tenant\Infrastructure\Twig\Components\: 'components/tenant/'
