<?php

declare(strict_types=1);

namespace GardenManager\Tests\Tenant\Domain\Entity;

use GardenManager\Tenant\Domain\Entity\Tenant;
use PHPUnit\Framework\Attributes\Group;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Uid\Ulid;

#[Group('unit')]
final class TenantTest extends TestCase
{
    #[Test]
    public function createWithAutoGeneratedId(): void
    {
        $tenant = Tenant::create(name: 'My Garden');

        self::assertSame('My Garden', $tenant->getName());
    }

    #[Test]
    public function createWithExplicitId(): void
    {
        $id = new Ulid();
        $tenant = Tenant::create(name: 'My Garden', id: $id);

        self::assertSame($id, $tenant->getId());
        self::assertSame('My Garden', $tenant->getName());
    }

    #[Test]
    public function setNameUpdatesName(): void
    {
        $tenant = Tenant::create(name: 'Old Name');

        $tenant->update('New Name');

        self::assertSame('New Name', $tenant->getName());
    }
}
